name: Upload Release

permissions:
  contents: write

on: 
  workflow_dispatch:
    inputs:
      SQLITE_VERSION:
        type: string
        description: "SQLite version to use"
        required: false
        default: ""

jobs:
  upload_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [29]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build Gradle args
        id: gradle_args
        run: |
          GRADLE_EXTRA_ARGS=""
          if [ -n "${{ github.event.inputs.SQLITE_VERSION }}" ]; then
            GRADLE_EXTRA_ARGS="$GRADLE_EXTRA_ARGS -PVERSION_NAME=${{ github.event.inputs.SQLITE_VERSION }}"
          fi
          echo "extra_args=$GRADLE_EXTRA_ARGS" >> $GITHUB_OUTPUT

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: x86
          script: ./gradlew connectedAndroidTest -PPUBLISH_TYPE=Final ${{ steps.gradle_args.outputs.extra_args }} --stacktrace

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-results ${{ matrix.api-level }}
          path: ./**/build/reports/androidTests/connected/**

      - name: Build AAR bundle
        id: build_aar
        run: ./gradlew bundleReleaseAar -PPUBLISH_TYPE=Final ${{ steps.gradle_args.outputs.extra_args }}

      - name: Upload release (manual build from master only)
        if: github.ref == 'refs/heads/master'
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNATURE_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNATURE_KEY_VALUE }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNATURE_KEY_PASSWORD }}
        run: ./gradlew publish -PPUBLISH_TYPE=Final -PmavenCentralAutomaticPublishing=false${{ steps.gradle_args.outputs.extra_args }}

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: SQLite ${{ steps.build_aar.outputs.SQLITE_VERSION }}
          path: ./sqlite-android/sqlite-android/build/outputs/aar/sqlite-android-decimal-*.aar
          
      - name: Create Git tag
        if: github.ref == 'refs/heads/master'
        run: |
          git tag ${{ steps.build_aar.outputs.SQLITE_VERSION }}
          git push origin ${{ steps.build_aar.outputs.SQLITE_VERSION }}

      - name: Create GitHub release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./sqlite-android/sqlite-android/build/outputs/aar/sqlite-android-decimal-${{ steps.build_aar.outputs.SQLITE_VERSION }}.aar
          tag_name: ${{ steps.build_aar.outputs.SQLITE_VERSION }}
          name: Release ${{ steps.build_aar.outputs.SQLITE_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}